export const Users = [
  {
    _id:"1",
    profilePicture: "assets/person/1.jpeg",
    username: "Safak Kocaoglu",
  },
  {
    _id:"2",
    profilePicture: "assets/person/2.jpeg",
    username: "Janell Shrum",
  },
  {
    _id:"3",
    profilePicture: "assets/person/3.jpeg",
    username: "Alex Durden",
  },
  {
    _id:"4",
    profilePicture: "assets/person/4.jpeg",
    username: "Dora Hawks",
  },
  {
    _id:"5",
    profilePicture: "assets/person/5.jpeg",
    username: "Thomas Holden",
  },
  {
    _id:"6",
    profilePicture: "assets/person/6.jpeg",
    username: "Shirley Beauchamp",
  },
  {
    _id:"7",
    profilePicture: "assets/person/7.jpeg",
    username: "Travis Bennett",
  },
  {
    _id:"635cbc1b4874eb940f5e803d",
    profilePicture: "assets/person/8.jpeg",
    username: "Kristen Thomas",
  },
  {
    _id:"9",
    profilePicture: "assets/person/9.jpeg",
    username: "Gary Duty",
  },
  {
    _id:"10",
    profilePicture: "assets/person/10.jpeg",
    username: "Safak Kocaoglu",
  },
];

export const Posts = [
  {
    _id: "1",
    description: "Love For All, Hatred For None.",
    image: "assets/post/1.jpeg",
    createdAt: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    _id: "2",
    image: "assets/post/2.jpeg",
    createdAt: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    _id: "3",
    description: "Every moment is a fresh beginning.",
    image: "assets/post/3.jpeg",
    createdAt: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    _id: "4",
    image: "assets/post/4.jpeg",
    createdAt: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    _id:"5",
    image: "assets/post/5.jpeg",
    createdAt: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    _id:"6",
    image: "assets/post/6.jpeg",
    createdAt: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    _id: "7",
    description: "Never regret anything that made you smile.",
    image: "assets/post/7.jpeg",
    createdAt: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    _id: "8",
    image: "assets/post/8.jpeg",
    createdAt: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    _id: "9",
    description: "Change the world by being yourself.",
    image: "assets/post/9.jpeg",
    createdAt: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    _id: "10",
    image: "assets/post/10.jpeg",
    createdAt: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
